In [3]:
import pandas as pd

## Criar dataframe com base nos Datasets

In [4]:
# Carregar Dataframe de Clientes (Customers)
df_customers = pd.read_csv('./datasets_aula/churn_customers.csv')

In [5]:
# Mostrar 5 primneiros registros do Dataframe
df_customers.head(5)

   customerID  gender  SeniorCitizen Partner Dependents
0  7590-VHVEG  Female              0     Yes         No
1  5575-GNVDE    Male              0      No         No
2  3668-QPYBK    Male              0      No         No
3  7795-CFOCW    Male              0      No         No
4  9237-HQITU  Female              0      No         No

In [6]:
# Mostrar os 5 ultimos registros de Clientes (Customers)
df_customers.tail(5)

      customerID  gender  SeniorCitizen Partner Dependents
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

In [7]:
# Mostrar as estrutura / schema do dataframe de clientes (customers)
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerID     7043 non-null   object
 1   gender         7043 non-null   object
 2   SeniorCitizen  7043 non-null   int64
 3   Partner        7043 non-null   object
 4   Dependents     7043 non-null   object
dtypes: int64(1), object(4)
memory usage: 275.2+ KB